#ifndef WI_FI_TYPES__H
#define WI_FI_TYPES__H

enum class ParseStatus { SUCCESSFUL_MATCH, 
SUCCESSFUL_PARTIAL_MATCH, 
SUCCESSFUL_NO_MATCH, 
FULL_BUFFER, 
FAILED_NO_READ, 
NOT_READABLE, 
FAILED_UNKNOWN_OPTION,
FAILED_NO_SELECTOR_SET };

#endif